import { Libre_Barcode_128, Sour_Gummy, Kablammo } from "next/font/google"
import "./globals.css";
import { redirect } from "next/navigation";

// 1. Use the function we imported and store the result in a varaible
// I'll export this font to use in a seperate file
export const libre_barcade_128 = Libre_Barcode_128({
  weight: '400',
  subsets: ['latin']
})

const sour_gummy = Sour_Gummy({
  subsets: ['latin']
})

const kablammo = Kablammo({
  subsets: ['latin'],
  // when giving a variable name, they have to start with --font
  // then pass the varible name to your body so the rest of the application can inherite it, and now you can reference the font in your css files.
  variable: '--font-kablammo'
})

console.log(libre_barcade_128)

export const metadata = {
  title: "Quote App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      className={`${sour_gummy.className} ${kablammo.variable}`}
      style={{
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        height: '100vh',
    }}>
        {children}
      </body>
    </html>
  );
}
