import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import Navigation from '@/components/NavBar'
import './globals.css'


export const metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`antialiased w-full h-full`}>
          <Navigation />
          <div className=''>
            {children}
          </div>
          <footer className=''>

          </footer>
        </body>
      </html>
    </ClerkProvider>
  )
}